### ISSUE TITLE
animeru

### ISSUE THREAD

**Issue by labideb** [Zeltorix/kodi#2]
Не воспроизводится видео. Вылетает с ошибкой. Такая беда на libreelec и пробовал на андроид смартфоне. Пару раз видел при запуски видео, проскакивает какое то уведомление "adaptive...".  Чудеса в том, что на чистой установке в debian работает нормально.

2023-12-08 23:16:49.345 T:12049   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.zeltorix.animeru/addon.py", line 17, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/storage/.kodi/addons/plugin.video.zeltorix.animeru/resources/lib/router.py", line 51, in router
                                                       view.play(model.play(link=params_dict['data']), "hls")
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.video.zeltorix.animeru/resources/lib/model.py", line 37, in play
                                                       hls = findall(r'atob\(".*"\),', data_2.text)[0].split('"')[1]
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
2023-12-08 23:16:49.552 T:808     error <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.zeltorix.animeru//?router=play&data=https%3A%2F%2Fanimeru.org%2Fpage-1-1472-prishedshiy-iz-drevnosti.html]

**Comment by Zeltorix** [comment]
> Не воспроизводится видео. Вылетает с ошибкой. Такая беда на libreelec и пробовал на андроид смартфоне.

Исправлено ещё вчера. На всякий случай повышу версию ещё раз, а то с raw данными, что то проблема в raw.githubusercontent.com. Вы можете принудительно обновить репозитории мои или агрегатора, тыкнув правой кнопкой мыши или долго зажав на сенсорном экране сами репозитории. В выпадающем меню выберете "Проверить обновления". KODI запросит файлик со списком последних версий плагинов и файлики хэшей md5, в надежде, что githubusercontent синхронизировался с github.

> Пару раз видел при запуски видео, проскакивает какое то уведомление "adaptive...". Чудеса в том, что на чистой установке в debian работает нормально.

Похоже, там где запускается плагин, в официальной репозитории нет inputstream.adaptive для данной ОС. От сюда можно взять [https://kodi.tv/addons/nexus/inputstream.adaptive/](url) для установки в ручную, но там нет для linux.
Для linux на основе Debian нужно установить в ручную, как отельный пакет. Они после этого появятся в меню плагинов KODI.
```
sudo apt update
sudo apt-get install kodi-inputstream-adaptive
```
Это плагин для ускорено запуска видео, плавного проигрывания. А другие плюшки на этом сайте с него не работают.

**Comment by labideb** [comment]
Спасибо большое. Действительно, не обновлялось поиском. Повторная установка
плагина помогла. Можно ещё несколько вопросов по плагинам? 1. У меня в
выборе "вид" нет привычного мне "постер". Я так понимаю, варианты видов вы
как то ограничивает в своих модулях? 2. Именно по animeru. Не могли бы вы
не ограничивать "Новинки" лишь одной страницей?  Не часто добираюсь до ТВ и
приходится лесть на сайт и смотреть, что я пропустил за время отсутствия,
так как колличество тайтлов у них велико. С уважением, Виктор

сб, 9 дек. 2023 г., 21:26 ZelToRiX ***@***.***>:

**Comment by Zeltorix** [comment]
> Можно ещё несколько вопросов по плагинам? 1. У меня в выборе "вид" нет привычного мне "постер". Я так понимаю, варианты видов вы как то ограничивает в своих модулях? 2. Именно по animeru. Не могли бы вы не ограничивать "Новинки" лишь одной страницей?

Задавайте, не стесняйтесь.
1. Да, ограничение есть. Если точнее это ограничения представлений контента в KODI. В зависимости от выбранного контента доступны определённые виды. В KODI есть files, songs, artists, albums, movies, tvshows, episodes, musicvideos, videos, images, games. По умолчанию использую videos. Если нужно, переопределю для каждой ветки меню tvshows. Как раз будет адаптация для смартфонов. Для меню, как раз будет возможность использовать вид "Баннер", большие кнопки по которым сложно промахнутся, да и с видом "Постер" будет удобней листать пальцем.

    - Добавил такую возможность, только для переписанных плагинов, остальные перепишутся со временем для этого.

2. Ограничение сделано, чтобы не нагружать лишними запросами сайт. Немного переделаю, будет возможность переходить по страницам.

**Comment by labideb** [comment]
Отлично! Если надо что то потестить под debian linux или libreelec (kodi
matrix, omega). Могу поднять у себя ещё какой нибудь osmc. Буду рад помочь
тестированием.

сб, 9 дек. 2023 г., 23:22 ZelToRiX ***@***.***>:

**Comment by Zeltorix** [comment]
> Отлично! Если надо что то потестить под debian linux или libreelec (kodi matrix, omega). Могу поднять у себя ещё какой нибудь osmc. Буду рад помочь тестированием. сб, 9 дек. 2023 г., 23:22 ZelToRiX ***@***.***>:

Если будешь искать настройки Видов.
Перенес настройки. Для всех аддонов настройки видов и разрешений. Ну почти для всех, в процессе.
