### ISSUE TITLE
VK.com : Следующая страница прямой трансляции недоступна

### ISSUE THREAD

**Issue by karlo2105** [Zeltorix/kodi#7]
Когда я нажимаю вкладку «Прямая трансляция» -> «Новости», следующая страница не отображается, а вместо этого перезагружается страница 1. Надеюсь, вы сможете это исправить.

С наилучшими пожеланиями.

**Comment by Zeltorix** [comment]
Исправлено.

**Comment by karlo2105** [comment]
Я подтверждаю, что сейчас это работает. ;-)
