### ISSUE TITLE
omega 21?

### ISSUE THREAD

**Issue by edvejak** [Zeltorix/kodi#8]
Any chance for omega 21?

**Comment by Zeltorix** [comment]
It is not entirely clear what the question is about.
Support for versions Matrix 19, Nexus 20, Omega 21, P... 22.

**Comment by edvejak** [comment]
![2024-07-24_1920x1080](https://github.com/user-attachments/assets/a0141b1a-1054-4d58-8fe4-a1552fc2ac1a)

**Comment by edvejak** [comment]
I have this warning in omega 21

**Comment by edvejak** [comment]
My fault. Everything works ok

**Comment by Zeltorix** [comment]
I'm glad that everything is settled.
